import { Activity, BadgeDollarSign, Landmark, TrendingUp, Users } from "lucide-react";

export const themes = [
  {
    href: "/atividade",
    title: "Atividade econômica",
    eyebrow: "Produção e crescimento",
    description: "Ritmo do ciclo, composição do PIB e difusão setorial do crescimento.",
    icon: Activity,
    color: "#087f5b",
    tint: "#e9f7f1",
    source: "BCB/IBGE (2026)",
  },
  {
    href: "/precos",
    title: "Preços",
    eyebrow: "Inflação",
    description: "Pressão inflacionária, difusão por grupos e custos ao produtor.",
    icon: BadgeDollarSign,
    color: "#1677a8",
    tint: "#e9f5fa",
    source: "IBGE/BCB (2026)",
  },
  {
    href: "/juros-credito",
    title: "Juros e crédito",
    eyebrow: "Condições financeiras",
    description: "Transmissão monetária, custo do crédito e risco de inadimplência.",
    icon: Landmark,
    color: "#176b87",
    tint: "#e9f3f6",
    source: "BCB (2026)",
  },
  {
    href: "/trabalho",
    title: "Mercado de trabalho",
    eyebrow: "Emprego e renda",
    description: "Ociosidade, renda real e qualidade da sustentação do consumo.",
    icon: Users,
    color: "#2b8a3e",
    tint: "#edf8ee",
    source: "IBGE (2026)",
  },
  {
    href: "/projecoes",
    title: "Cenários e projeções",
    eyebrow: "Trajetórias prospectivas",
    description: "Cenários para consumo das famílias sob juros, inflação e riscos externos.",
    icon: TrendingUp,
    color: "#0b7285",
    tint: "#e6f6f8",
    source: "IBGE/BCB (2026)",
  },
];
